"use client";

import CollapsibleSection from "./CollapsibleSection";

interface DataPhase {
  no: number;
  category: string;
  name: string;
  exampleObjects?: string;
  dependencies?: string;
  notes?: string;
}

const dataDeploymentSequence: DataPhase[] = [
  // Foundation / Reference Data
  { no: 1, category: "Foundation", name: "Users", exampleObjects: "User", dependencies: "Active and integration users, ensure Profile, Role, License pre-set", notes: "Load first for OwnerId references" },
  { no: 2, category: "Foundation", name: "Profiles / Roles / Groups", exampleObjects: "Role, Group", dependencies: "Usually pre-deployed in metadata; verify IDs for references", notes: "System-generated, verify mapping" },
  { no: 3, category: "Foundation", name: "Queues", exampleObjects: "Group (Type='Queue'), QueueSobject", dependencies: "Required for Case/Lead assignment", notes: "Load before Cases" },
  { no: 4, category: "Foundation", name: "Territories (if used)", exampleObjects: "Territory2, Territory2Model", dependencies: "Optional, load before Account sharing", notes: "Only if Territory Management enabled" },
  { no: 5, category: "Foundation", name: "Record Types", exampleObjects: "RecordType", dependencies: "System-generated by metadata but export for mapping", notes: "Map old→new RecordTypeIds" },
  { no: 6, category: "Foundation", name: "Custom Metadata / Settings", exampleObjects: "Custom Metadata, Custom Setting", dependencies: "Optional reference lookups", notes: "If used for data validation" },
  
  // Master Data
  { no: 7, category: "Master Data", name: "Accounts", exampleObjects: "Account", dependencies: "References: User (OwnerId)", notes: "Parent for most objects" },
  { no: 8, category: "Master Data", name: "Contacts", exampleObjects: "Contact", dependencies: "References: Account, User (OwnerId)", notes: "Load after Accounts" },
  { no: 9, category: "Master Data", name: "Person Accounts", exampleObjects: "Account (IsPersonAccount=true)", dependencies: "Special handling: enable before load", notes: "Requires Person Accounts feature" },
  { no: 10, category: "Master Data", name: "Leads", exampleObjects: "Lead", dependencies: "No dependency; can map to converted Accounts later", notes: "Can load independently" },
  { no: 11, category: "Master Data", name: "Campaigns", exampleObjects: "Campaign", dependencies: "References: User", notes: "Load before Campaign Members" },
  { no: 12, category: "Master Data", name: "Products / Pricebooks", exampleObjects: "Product2, Pricebook2, PricebookEntry", dependencies: "Product2 first, then Pricebook2, then PricebookEntry", notes: "Sequential: Products → Pricebooks → Entries" },
  { no: 13, category: "Master Data", name: "Assets / Locations", exampleObjects: "Asset, Location", dependencies: "References: Account, Contact, Product", notes: "Load after Accounts, Contacts, Products" },
  
  // Transactional / Operational Data
  { no: 14, category: "Transactional", name: "Opportunities", exampleObjects: "Opportunity", dependencies: "Account, Contact (PrimaryContactId), Pricebook2", notes: "Load after Accounts, Contacts, Pricebooks" },
  { no: 15, category: "Transactional", name: "Quotes & Quote Line Items", exampleObjects: "Quote, QuoteLineItem", dependencies: "Opportunity, Product2", notes: "Load Quotes first, then Line Items" },
  { no: 16, category: "Transactional", name: "Orders & Order Line Items", exampleObjects: "Order, OrderItem", dependencies: "Account, PricebookEntry", notes: "Load Orders first, then Line Items" },
  { no: 17, category: "Transactional", name: "Contracts", exampleObjects: "Contract", dependencies: "Account, Opportunity (optional)", notes: "Load after Accounts" },
  { no: 18, category: "Transactional", name: "Cases", exampleObjects: "Case", dependencies: "Account, Contact, User (Owner), Queue", notes: "Load after Accounts, Contacts, Queues" },
  { no: 19, category: "Transactional", name: "Solutions / Knowledge", exampleObjects: "Solution, KnowledgeArticleVersion", dependencies: "Ensure Knowledge enabled", notes: "Requires Knowledge feature" },
  { no: 20, category: "Transactional", name: "Tasks / Events", exampleObjects: "Task, Event", dependencies: "RelatedTo (Account, Opportunity, Case, etc.), WhoId (Contact/Lead)", notes: "Load after all parent objects" },
  
  // Related / Linking Data
  { no: 21, category: "Related Data", name: "Campaign Members", exampleObjects: "CampaignMember", dependencies: "Campaign, Lead/Contact", notes: "Many-to-many relationship" },
  { no: 22, category: "Related Data", name: "Opportunity Contact Roles", exampleObjects: "OpportunityContactRole", dependencies: "Opportunity, Contact", notes: "Junction object" },
  { no: 23, category: "Related Data", name: "Account Team Members", exampleObjects: "AccountTeamMember", dependencies: "Account, User", notes: "Load after Accounts and Users" },
  { no: 24, category: "Related Data", name: "Opportunity Team Members", exampleObjects: "OpportunityTeamMember", dependencies: "Opportunity, User", notes: "Load after Opportunities" },
  { no: 25, category: "Related Data", name: "Case Team Members", exampleObjects: "CaseTeamMember", dependencies: "Case, User", notes: "Load after Cases" },
  { no: 26, category: "Related Data", name: "Quote Documents / Attachments", exampleObjects: "ContentVersion, ContentDocumentLink", dependencies: "Quote, User", notes: "Load after Quotes" },
  { no: 27, category: "Related Data", name: "Notes / Files", exampleObjects: "Note, ContentDocumentLink", dependencies: "Related parent object", notes: "Load after all parent objects" },
  { no: 28, category: "Related Data", name: "Custom Junctions", exampleObjects: "Any `__c` object with two lookups", dependencies: "Load after both parents", notes: "Custom many-to-many objects" },
  
  // Secondary / Derived Data
  { no: 29, category: "Derived Data", name: "PricebookEntry History", exampleObjects: "PricebookEntryHistory", dependencies: "Product2, PricebookEntry", notes: "Historical records" },
  { no: 30, category: "Derived Data", name: "Opportunity History", exampleObjects: "OpportunityFieldHistory", dependencies: "Opportunity", notes: "Field history tracking" },
  { no: 31, category: "Derived Data", name: "Case History / Email Messages", exampleObjects: "CaseHistory, EmailMessage", dependencies: "Case", notes: "Historical and email data" },
  { no: 32, category: "Derived Data", name: "Feed Items (Chatter)", exampleObjects: "FeedItem", dependencies: "ParentId (Account, Opportunity, etc.)", notes: "Requires Chatter enabled" },
  { no: 33, category: "Derived Data", name: "Approval Requests / Process Instances", exampleObjects: "ProcessInstance, ProcessInstanceStep", dependencies: "Parent records", notes: "Workflow/Flow execution history" },
  
  // Reference Rebuilds / Finalization
  { no: 34, category: "Finalization", name: "Sharing Rules (Manual)", exampleObjects: "ManualShare, AccountShare", dependencies: "Recreate only if needed", notes: "Manual sharing records" },
  { no: 35, category: "Finalization", name: "Recalculate Rollups", exampleObjects: "Opportunity.Amount, Account.TotalValue__c", dependencies: "Trigger recalculations post-load", notes: "Formula and rollup fields" },
  { no: 36, category: "Finalization", name: "Activate Triggers / Validation Rules", exampleObjects: "Post-load re-enable", dependencies: "Disable pre-load to avoid errors", notes: "Re-enable automation" },
  { no: 37, category: "Finalization", name: "Delta Loads / Reconciliation", exampleObjects: "Audit table", dependencies: "After all parent data present", notes: "Final data sync" },
];

export default function DataDeploymentSequence() {
  // Group by category
  const phasesByCategory = dataDeploymentSequence.reduce((acc, phase) => {
    if (!acc[phase.category]) acc[phase.category] = [];
    acc[phase.category].push(phase);
    return acc;
  }, {} as Record<string, DataPhase[]>);

  return (
    <CollapsibleSection title="Recommended Data Deployment Sequence" defaultOpen={false}>
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="mb-4">
          <p className="text-sm text-gray-600 mb-4">
            This is the recommended order for loading data records into Salesforce. Follow this sequence to maintain referential integrity and minimize migration failures.
          </p>
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
            <h4 className="text-sm font-semibold text-blue-900 mb-2">Execution Notes</h4>
            <ul className="text-xs text-blue-800 space-y-1 list-disc list-inside">
              <li>Disable validation rules, triggers, and workflows during migration</li>
              <li>Use <strong>upsert</strong> with external IDs wherever possible</li>
              <li>Maintain an <strong>old→new ID mapping table</strong> for lookups (AccountId, ContactId, etc.)</li>
              <li>Run User, Queue, and RecordType mapping first</li>
              <li>Load in <strong>batches</strong> (e.g., Accounts → Contacts → Opportunities → Quotes → Cases)</li>
              <li>Re-enable automation and verify counts post-load</li>
            </ul>
          </div>
        </div>
        
        <div className="space-y-6">
          {Object.entries(phasesByCategory).map(([category, phases]) => (
            <div key={category} className="border rounded-lg p-4">
              <h4 className="text-sm font-semibold text-gray-900 mb-3 pb-2 border-b">
                {category} ({phases.length} phases)
              </h4>
              <div className="space-y-2">
                {phases.map((phase) => (
                  <div
                    key={phase.no}
                    className="flex items-start gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-sm font-semibold">
                      {phase.no}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1">
                          <div className="text-sm font-medium text-gray-900">{phase.name}</div>
                          {phase.exampleObjects && (
                            <div className="text-xs text-gray-600 mt-1 font-mono">{phase.exampleObjects}</div>
                          )}
                          {phase.dependencies && (
                            <div className="text-xs text-gray-500 mt-1">
                              <span className="font-medium">Dependencies:</span> {phase.dependencies}
                            </div>
                          )}
                          {phase.notes && (
                            <div className="text-xs text-gray-500 mt-1 italic">{phase.notes}</div>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </CollapsibleSection>
  );
}

